### ISSUE TITLE
[TODO] this will not work (or work crappy for non-seekable steams like http)

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/data#126] opened 2021-12-10 20:08 UTC
This issue is generated from the TODO line
https://github.com/pytorch/data/blob/f102d25f9f444de3380c6d49bf7aaf52c213bb1f/build/lib/torchdata/datapipes/iter/util/hashchecker.py#L39
cc @VitalyFedyunin

**Comment by NivekT** [comment] 2021-12-30 20:26
Closing this because it is a duplicate of #133

**Closed by NivekT** 2021-12-30 20:26 UTC
Labels: todo
