### ISSUE TITLE
[RFC] Disable the multiple Iterators per IterDataPipe (Make Iterator singleton)

### ISSUE THREAD

**Issue by ejguan** [pytorch/data#45] opened 2021-10-05 21:14 UTC
This is the initial draft. I will complete it shortly.

State of Iterator is attached to each IterDataPipe instance. This is super useful for:
- Determinism
- Snapshotting
- Benchmarking -> It becomes easier to register each DataPipe since they have different ID in the graph.

Implementation Options:
- Each DataPipe has an attribute of `_iterator` as the place holder for `__iter__` calls.
- Implement `__next__`. (My Preference)
  - It would make the instance pickable. Previously generator function (`__iter__`) is not picklable -> Help multiprocessing and snapshotting)
  - `__iter__` return `self` (`Forker(self)` may be another option, not 100% sure)
  - IMO, this is super useful as we can track the number of `__next__` call to do a fast forward. The state of iteration is attached to DataPipe instance, rather than a temporary instance created from `__iter__`, which we couldn't track the internal state. (We can easily track states like RNG, iteration number, buffer, etc. as they are going to be attached to `self` instance)
  - As source DataPipe is attached to each DataPipe, but the actual iteration happens on Iterator level. The graph constructed by DataLoaderV2 doesn't match the actual execution graph.

DataLoader trigger Error if there are two DataPipe instance with same id in the graph. (Another option is DataLoader do an automatically fork)
Users should use Forker for each DataPipe want to have single DataPipe twice in the graph.

cc: @VitalyFedyunin @NivekT

**Comment by ejguan** [comment] 2022-02-16 22:40
Looking at the code base, I still think it would be better if we make IterDataPipe as a singleton Iterator. Like our implementation of `Fork`, `Demux` and etc. They have already been singleton. If one child datapipe is referenced multiple times, `_Fork`, `_Demux` won't provide the same time for each reference of the child datapipe. This is crucial because we are providing different behaviors for DataPipes.


I have to admit that we need to think about a way to make sure multiple reference of a DataPipe can be also achieved in eager mode (datapipe iteration).

**Comment by NivekT** [comment] 2022-02-16 22:47
I spent a lot time thinking about this as well, and I think we will have to have one iterator per DataPipe.

Some other useful, potentially features:
- Automatically reset the iterator when all elements are yielded (this seems important)
- Automatically fork when a second iterator is wanted (may be bad, not sure how often users actually want multiple iterators per DataPipe, manual forking should be fine IMO)

If we end up with `_iterator` implementation, we can use a decorator to register when an iterator is created and is in use.

**Comment by ejguan** [comment] 2022-02-16 22:50
> Automatically reset the iterator when all elements are yielded (this seems important)

The missing feature in my mind is to reset in the middle of iteration. This can not be achieved by current generator function in `__iter__`.

**Comment by NivekT** [comment] 2022-04-15 21:15
Implementation aside. I believe the followings should be the expected behavior. Let's focus on DataPipes that produce a single DataPipe output first (i.e. excluding DataPipes that produce multiple child DataPipes).

```python
"""
This serves as the example for any DataPipe that only has one child DataPipe.
"""
# 1. An iterator can be created from a DP and iterated through (each iterator exhausts after iterated through once).
source_dp = dp.iter.IterableWrapper(range(10))
it1 = iter(source_dp)
print(f"Iterating through iterator1: {list(it1)}")
it1 = iter(source_dp)  # This should not raise any warning
print(f"Creating a new iterator from the same DataPipe and iterating through again: {list(it1)}")
it1 = iter(source_dp)  # This should not raise any warning
print(f"Re-creating but only getting the first element of iterator1: {next(it1)}")

# 2. Initializing a second iterator should invalidate the first iterator, raising a warning if the first is not
#    exhausted. Moreover, if `next()` is called on the first iterator again, an error should be raised.
print("\nCreating iterator 2...")
it2 = iter(source_dp)  # This should raise a warning? Only if the first is not exhausted?
print("Calling __next__ on iterator 1:")
next(it1)  # This should raise an error, since `it1` should be invalidated
print(f"Created iterator 2 from the same DataPipe and iterating through: {list(it2)}")
```

It should return the following messages:
```
Iterating through iterator1: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Creating a new iterator from the same DataPipe and iterating through again: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Re-creating but only getting the first element of iterator1: 0

Creating iterator 2...
<A warning should be raised here>
Calling __next__ on iterator 1:
<An exception should be raised here>
Created iterator 2 from the same DataPipe and iterating through: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```

A note on exception and warning:
1. I think an exception should always be raised if the user tries to use an invalidated iterator again (e.g. `it1`)
2. I am leaning towards raising a warning whenever a new iterator `it2` is created but the old iterator `it1` is not exhausted
     - There should be an API to globally suppress the warnings and automatic suppression within notebook mode
     - Alternatively, we can never raise a warning, which can be fine if the exception message is sufficient

Let me know if there is any disagreement that the behavior within the example above.

**Comment by NivekT** [comment] 2022-04-15 21:46
Here is the expected behavior for DataPipes that produce multiple child DataPipes
```python
"""
This serves as the example for any DataPipe that have multiple child DataPipes (e.g. `fork`, `demux`, `unzip`).
"""
# 1. Iterator can be created and iterated through for the child
source_dp = dp.iter.IterableWrapper(range(10))
child_dp1, child_dp2 = source_dp.fork(2)
it1, it2 = iter(child_dp1), iter(child_dp2)
print(f"Iterating through child_iterator1: {list(it1)}")
print(f"Iterating through child_iterator2: {list(it2)}")
it1, it2 = iter(child_dp1), iter(child_dp2)
print(f"Iterating through child_iterator1 again: {list(it1)}")
print(f"Iterating through child_iterator2 again: {list(it2)}")
it1, it2 = iter(child_dp1), iter(child_dp2)
print(f"Re-creating but only getting the first element of iterator1: {next(it1)}")

# 2. If you initialize a second iterator for a child DataPipe, you will need to either:
#    i. start a second buffer (since you need to read the `source_dp` from the beginning again), and
#       invalidate the old iterator that was created from the same child DataPipe
#       I think this will work, but the logic will be pretty complicated
print("Calling `iter(child_dp1)`")
it1_new = iter(child_dp1)  # `it1` must be invalidated, a warning is raised
next(it1)  # This should raise an error
# If we choose to start a second buffer, then the other child iterators do not need to be invalidated
next(it2)  # This will not raise an error

#  Alternatively, we can:
#    ii. Invalidate all previous child iterators
it1_new = iter(child_dp1)  # both `it1` and `it2` are invalidated, an warning is raised
next(it1)  # This should raise an error
next(it2)  # This should raise an error
```
We should decide between the behavior stated in 2.i. and 2.ii.

2.ii is a simpler implementation, is there any case where the user would prefer 2.i. over 2.ii?
The only one I can think of is when they want to re-read the same child DataPipe multiple times before interacting with the others.

**Comment by ejguan** [comment] 2022-04-18 16:33
> ```python
> # 2. Initializing a second iterator should invalidate the first iterator, raising a warning if the first is not
> #    exhausted. Moreover, if `next()` is called on the first iterator again, an error should be raised.
> ```

I have a concern. This design would only solve the single-branch DataPipe line. If a DataPipe instance is reference twice, users would experience Exception during iteration.
For example:
```
dp = IterableWrapper(range(10))
dp1 = dp.map(fn1)
dp2 = dp.map(fn2)
dp3 = dp1.zip(dp2)
```
When we iterate over `dp3`, two iterators of `dp` would be created.

I would say the ideal solution is to have a switch between singleton and non-singleton mode. When users are iterating over `IterDataPipe`, we would allow users to create multiple iterators from a single DataPipe instnace. When users provide `IterDataPipe` to `DataLoader`, we would prohibit `IterDataPipe` being referenced multiple times for multiple iterators.

TBH, I am not sure how difficult this design would be.

**Comment by NivekT** [comment] 2022-04-18 17:11
> > ```python
> > # 2. Initializing a second iterator should invalidate the first iterator, raising a warning if the first is not
> > #    exhausted. Moreover, if `next()` is called on the first iterator again, an error should be raised.
> > ```
> 
> I have a concern. This design would only solve the single-branch DataPipe line. If a DataPipe instance is reference twice, users would experience Exception during iteration. For example:
> 
> ```
> dp = IterableWrapper(range(10))
> dp1 = dp.map(fn1)
> dp2 = dp.map(fn2)
> dp3 = dp1.zip(dp2)
> ```
> 
> When we iterate over `dp3`, two iterators of `dp` would be created.

I agree that will happen. Users will have to explicitly fork `dp1` if they want to use it in twice in this case.

> I would say the ideal solution is to have a switch between singleton and non-singleton mode. When users are iterating over `IterDataPipe`, we would allow users to create multiple iterators from a single DataPipe instnace. When users provide `IterDataPipe` to `DataLoader`, we would prohibit `IterDataPipe` being referenced multiple times for multiple iterators.
> 
> TBH, I am not sure how difficult this design would be.

Does this mean:
1. When `dp3` from the example above is passed into `DataLoader`, an exception will be raised (because there are multiple DataPipes referencing to `dp1`)? 
2. Alternatively, do you mean that only the final DataPipe `dp3` cannot have multiple iterators in `DataLoader`?

If 1) is the case, one potential solution is that when a graph is constructed and such behavior is detected. `DataLoader` can automatically fork `dp1` into two such that this will no longer be an issue.

**Comment by ejguan** [comment] 2022-04-18 17:16
> * When `dp3` from the example above is passed into `DataLoader`, an exception will be raised (because there are multiple DataPipes referencing to `dp1`)?

I would expect `DataLoader2` would automatically `fork` dp for the graph. Then, no exception would be raised.

**Comment by NivekT** [comment] 2022-04-18 17:38
IIUC, what should happen is:
1. `DataLoader2` will automatically `fork` a DataPipe if there are multiple references by other `DataPipes` in the graph
2. Even then, we want to switch on a singleton mode within DataLoader. The mode will have the behaviors that I outlined above (i.e. ensure that each iterator is still valid whenever it is used, invalidate the first when a new iterator is created).
    - Will this still be necessary if `DataLoader2`'s forking is working 100% properly? I think it may potentially cover some edge cases if users do something unexpected with the DataPipes.

**Comment by NivekT** [comment] 2022-04-19 20:16
I chatted with @VitalyFedyunin offline.

1. For the case where there are multiple child DataPipes as output, when a new iterator is created for one of the child DataPipes, we will invalidate all previous child DataPipes immediately. This is because by starting a new iterator, the `main_datapipe` needs to start reading from the beginning again in order to provide that child DataPipe with the samples that it needs.
    - One alternative is to check that child's buffer to see if there are more items to yield, and if yes, delay the invalidation. Though this doesn't really address the issue and just delay the exception. Invalidating other child DataPipes' iterators immediately seem to be better.
2. DataPipes should always be in singleton mode. For the multiple references example that @ejguan provided above, @VitalyFedyunin suggests that DataLoader2 should suggest forking to user rather than trying to automatically fork. This should be part of the DataPipe graph linter as well.
    - DataLoader1 should raise exception when multiple references situation arises.

@ejguan Let us know if you have any thoughts, especially about 2.

**Comment by ejguan** [comment] 2022-04-19 20:33
> DataPipes should always be in singleton mode. For the multiple references example that @ejguan provided above, @VitalyFedyunin suggests that DataLoader2 should suggest forking to user rather than trying to automatically fork. This should be part of the DataPipe graph linter as well.

This is my initial thinking but I am tentative about it simply because this is going to be a huge BC breaking change. If everyone agrees on it, I would support to do it ASAP. And, we need to update our documentation about implementing `IterDataPipe`.

**Comment by VitalyFedyunin** [comment] 2022-04-20 18:39
> > DataPipes should always be in singleton mode. For the multiple references example that @ejguan provided above, @VitalyFedyunin suggests that DataLoader2 should suggest forking to user rather than trying to automatically fork. This should be part of the DataPipe graph linter as well.
> 
> This is my initial thinking but I am tentative about it simply because this is going to be a huge BC breaking change. If everyone agrees on it, I would support to do it ASAP. And, we need to update our documentation about implementing `IterDataPipe`.

Agree with ASAP argument.

**Comment by NivekT** [comment] 2022-04-20 19:11
Just to be clear, I think this means:
1. Keep the existing DataPipes implementations as they are, but we will add checks to invalidate an old iterator when a new one is created (i.e. always be in singleton mode)
    - WIP implmentation: https://github.com/pytorch/pytorch/pull/70479
3. Update the documentation to recommend users to return `self` within `__iter___` for custom `IterDataPipe`

**Comment by ejguan** [comment] 2022-04-20 20:14
> 1. Keep the existing DataPipes implementations as they are, but we will add checks to invalidate an old iterator when a new one is created (i.e. always be in singleton mode)

For the PR, could you verify all our existing customers' code would behave normally?

> 2\. Update the documentation to recommend users to return `self` within `__iter___` for custom `IterDataPipe`

Just ignore my argument above. I misunderstood the approach in the PR. We can leave the API as it is. But, we need to document the behavior of the singleton iterator.

**Comment by NivekT** [comment] 2022-04-22 14:21
cc: @NicolasHug in case you have any concern about this

**Comment by NicolasHug** [comment] 2022-04-25 15:27
>  2. Update the documentation to recommend users to return self within __iter___ for custom IterDataPipe

In torchvision's datasets, `__iter__` yields from a private `._dp` attribute and does not return self. Would this be a problem?

https://github.com/pytorch/vision/blob/6d85d74be6ac72b2ac3057d85d8ae0004fa0de3f/torchvision/prototype/datasets/utils/_dataset.py#L41:L42


CC @pmeier

**Comment by NivekT** [comment] 2022-04-25 15:39
> > 2. Update the documentation to recommend users to return self within **iter**_ for custom IterDataPipe
> 
> In torchvision's datasets, `__iter__` yields from a private `._dp` attribute and does not return self. Would this be a problem?
> 
> https://github.com/pytorch/vision/blob/6d85d74be6ac72b2ac3057d85d8ae0004fa0de3f/torchvision/prototype/datasets/utils/_dataset.py#L41:L42
> 
> CC @pmeier

I think not returning `self` from there will still work (but I'll certain test it out before I try to land anything). It will prevent users from having multiple active iterators referencing the same Dataset:
```python
some_dataset = ...
it1 = iter(some_dataset)  # This is fine
it2 = iter(some_dataset)  # This will invalidate `it1`
```

**Comment by NivekT** [comment] 2022-05-19 20:37
Fixed by:
https://github.com/pytorch/pytorch/pull/75995
https://github.com/pytorch/pytorch/pull/70479

**Closed by NivekT** 2022-05-19 20:37 UTC

**Comment by NivekT** [comment] 2022-05-25 21:45
If multiple references to the same `IterDataPipe` is necessary, please use `.fork()` to create separate instances.

```python
main_dp = IterableWrapper(range(10))
dp1 = main_dp.map(lambda x: x + 1)
dp2 = main_dp.map(lambda x: x * 2)
final_dp = dp1.zip(dp2)  # This uses two `IterDataPipes` that both use`main_dp`
list(final_dp). # This will raise a `RunTimeError` 
```

Add `.fork()` and this will work as intended:
```python
main_dp = IterableWrapper(range(10))
main_dp1, main_dp2 = main_dp.fork(num_instances=2)
dp1 = main_dp1.map(lambda x: x + 1)
dp2 = main_dp2.map(lambda x: x * 2)
final_dp = dp1.zip(dp2)
list(final_dp)
```

**Comment by NivekT** [comment] 2022-06-10 19:22
Note to future readers, these linked PRs contain BC-breaking notes that describe the behavior before and after in details:
* https://github.com/pytorch/pytorch/pull/70479
* https://github.com/pytorch/pytorch/pull/75995
