### ISSUE TITLE
Allow passing in init_process_group kwargs to fullsync datapipe

### ISSUE THREAD

**Issue by vedantroy** [pytorch/data#868] opened 2022-10-30 05:10 UTC
### 🚀 The feature

The following issue on the Ray forums describes the problem: https://discuss.ray.io/t/get-distributed-process-group-timeout-when-using-torch-trainer-fullsynciterdatapipe/8075.

The TL;DR is, I need to be able to pass in arguments to this line: https://github.com/pytorch/data/blob/4ea88d1fb4d279def9213a23b054b4e7d46d5b3d/torchdata/datapipes/iter/util/prefetch.py#L174 in order to prevent hanging

### Motivation, pitch

Would allow for me to intervene in the process group initialization. This would prevent hanging.

**Comment by ejguan** [comment] 2022-11-01 13:51
I think it's reasonable to provide such argument.
And, I am curious why do you think providing a process_group would prevent hanging? I am generally interested in what would be the root cause of hanging, so that I might be able to provide a proper fix. I feel like sub-pg should be fine for the most of use cases.

**Comment by vedantroy** [comment] 2022-11-16 03:13
Hm, I assumed that the issue was that I'm using Ray (https://docs.ray.io/en/latest/train/train.html), and I just needed to configure some environment variables for the process group or something like that. But I could definitely be wrong.

One thing of interest (maybe) is that the bug does not happen the first time I run my training script, instead it happens the 2nd time I run my training script.

If you know how to use ray, here's a reproduction:

```
import ray
import ray.train.torch as ray_torch
import torchdata.datapipes.iter as pipes
from ray.air import ScalingConfig
from torch.utils.data import DataLoader

ray.init()


def loader():
    pipe = pipes.IterableWrapper(list(range(2000)))
    pipe = pipe.batch(5)
    pipe = pipe.fullsync()
    return DataLoader(pipe, batch_size=None, num_workers=5)


def train_loop():
    dl = loader()
    print("TRYING TO CREATE SAMPLE")
    x = next(iter(dl))
    print("THIS LINE NEVER GETS PRINTED")


trainer = ray_torch.TorchTrainer(
    train_loop_per_worker=train_loop,
    scaling_config=ScalingConfig(num_workers=2, use_gpu=False),
)
trainer.fit()
```

I suspect the issue could also be on the Ray end, so I've filed an issue there as well: https://github.com/ray-project/ray/issues/30324

**Comment by ejguan** [comment] 2022-11-21 16:29
Thanks for providing the script. It's feasible for us to provide an argument to this DataPipe. However, it's not clear to me if this is going to solve the problem you have encountered.
Could you please elaborate what is the error/issue running your script? Hanging or Error raised?

**Comment by vedantroy** [comment] 2022-11-27 02:18
> Thanks for providing the script. It's feasible for us to provide an argument to this DataPipe. However, it's not clear to me if this is going to solve the problem you have encountered. Could you please elaborate what is the error/issue running your script? Hanging or Error raised?

@ejguan 
There's hanging, and if I wait 30 or so minutes -- that line will eventually throw a `Timeout` error.

**Comment by ejguan** [comment] 2022-11-28 14:57
> There's hanging, and if I wait 30 or so minutes -- that line will eventually throw a `Timeout` error.

When did hanging happen? At the time of `dist.new_group` or after the first epoch?

**Comment by vedantroy** [comment] 2022-11-29 00:29
> > There's hanging, and if I wait 30 or so minutes -- that line will eventually throw a `Timeout` error.
> 
> When did hanging happen? At the time of `dist.new_group` or after the first epoch?

At the time of. The example shows that it never gets passed the initialization phase to actual data loading

**Comment by ejguan** [comment] 2022-12-05 16:07
After checking your log, I am more convinced that pytorch distributed group is not fully initialized. I can see the log for setting up rank 0 but not rank 1
```
Setting up process group for: env:// [rank=0, world_size=2]
```
Then, it leads to the `DataLoader2` on rank 0 is stuck at the beginning of iteration because the Process Group on rank 1 has not been created yet.

**Comment by vedantroy** [comment] 2022-12-13 23:31
@ejguan  This could be the case. But the confusing part is when I remove this line, the code works fine -- which means that somehow using the `fullsync` pipe would be messing up process group initialization?

As such, I think the problem is with the `fullsync` data pipe, since if the underlying issue was that process groups were not being initialized, I would expect my code to still break if I removed the `fullsync`.

Is there anything I can do to assist w/ debugging this issue?

**Comment by ejguan** [comment] 2022-12-14 15:40
Without adding `fullsync`, could you pls add `torch.distributed.get_rank()` in your `train_loop` to see if all ranks are presented.

**Comment by matthewdeng** [comment] 2022-12-15 02:08
> After checking your log, I am more convinced that pytorch distributed group is not fully initialized. I can see the log for setting up rank 0 but not rank 1
> 
> ```
> Setting up process group for: env:// [rank=0, world_size=2]
> ```
> 
> Then, it leads to the `DataLoader2` on rank 0 is stuck at the beginning of iteration because the Process Group on rank 1 has not been created yet.

@ejguan as a quick note on this - Ray Train intentionally [only logs on world rank 0](https://github.com/ray-project/ray/blob/master/python/ray/train/torch/config.py#L85-L94) to reduce the log output, so the process group should still also be initialized on the other worker as well. 

@vedantroy another thing you can try is to use the [stack trace functionality](https://docs.ray.io/en/master/ray-observability/monitoring-debugging/profiling.html#python-cpu-profiling-in-the-dashboard) that was recently added to Ray 2.2 to see exactly where the hang is happening in the training process.

**Comment by ejguan** [comment] 2022-12-15 15:00
@vedantroy 

I am still unsure about this problem because `DataLoader` itself has another `dist.new_group` in 
https://github.com/pytorch/pytorch/blob/b92975a6f305d32151e50f4625ea6f56ff7a8efb/torch/utils/data/dataloader.py#L575
And, this line is called before the `new_group` in `fullsync`.

**Comment by vedantroy** [comment] 2022-12-16 01:10
@ejguan ok, I added print statements before and after both of the process group initializations, and the first one succeeds, but the second one fails.

Here's something that's interesting:
- the first process group initialization happens twice (I'm guessing once for each rank)
- the second one happens 10 times (or more accurately, starts but never finishes 10 times) -- which corresponds to 2 * 5 = # ranks * # workers

so it looks like the main dataloader process can spawn process groups, but the worker processes cannot for some reason.

Does this help?

Here's my logs:

```
(RayTrainWorker pid=39810) 2022-12-15 17:10:21,540      INFO config.py:87 -- Setting up process group f
or: env:// [rank=0, world_size=2]                                                                      
(RayTrainWorker pid=39811) rank: 1                                                                     
(RayTrainWorker pid=39811) TRYING TO CREATE SAMPLE
(RayTrainWorker pid=39811) INITIALIZATION GLOO IN DATALOADER
(RayTrainWorker pid=39811) FINISHED INITIALIZATION GLOO IN DATALOADER
(RayTrainWorker pid=39810) rank: 0
(RayTrainWorker pid=39810) TRYING TO CREATE SAMPLE
(RayTrainWorker pid=39810) INITIALIZATION GLOO IN DATALOADER
(RayTrainWorker pid=39810) FINISHED INITIALIZATION GLOO IN DATALOADER
(RayTrainWorker pid=39811) INITIALIZING GLOO IN DATAPIPEINITIALIZING GLOO IN DATAPIPE
(RayTrainWorker pid=39811) 
(RayTrainWorker pid=39811) INITIALIZING GLOO IN DATAPIPE
(RayTrainWorker pid=39811) INITIALIZING GLOO IN DATAPIPE
(RayTrainWorker pid=39811) INITIALIZING GLOO IN DATAPIPE
(RayTrainWorker pid=39810) INITIALIZING GLOO IN DATAPIPE
(RayTrainWorker pid=39810) INITIALIZING GLOO IN DATAPIPEINITIALIZING GLOO IN DATAPIPE
(RayTrainWorker pid=39810) 
(RayTrainWorker pid=39810) INITIALIZING GLOO IN DATAPIPE
(RayTrainWorker pid=39810) INITIALIZING GLOO IN DATAPIPE
```

**Comment by ejguan** [comment] 2022-12-16 01:53
Okay, I know what's going on her. The `fullsync` datapipe are spawned `num_workers` times, which causes the problem. I am working on a solution for it using DataLoader2. Will post when it becomes available.

**Comment by vedantroy** [comment] 2022-12-16 02:35
> Okay, I know what's going on her. The `fullsync` datapipe are spawned `num_workers` times, which causes the problem. I am working on a solution for it using DataLoader2. Will post when it becomes available.

@ejguan, sounds good -- is there a short term fix I can use here, right now I need to manually restart my training process every epoch.

**Comment by ejguan** [comment] 2022-12-16 16:21
> > Okay, I know what's going on her. The `fullsync` datapipe are spawned `num_workers` times, which causes the problem. I am working on a solution for it using DataLoader2. Will post when it becomes available.
> 
> @ejguan, sounds good -- is there a short term fix I can use here, right now I need to manually restart my training process every epoch.

One hack would be
```py
def loader():
    pipe = pipes.IterableWrapper(list(range(2000)))
    pipe = pipe.batch(5)
    dl = DataLoader(pipe, batch_size=None, num_workers=5)
    pipe = IterableWrapper(dl).fullsync()
    return pipe
```
I think I am able to send a patch by the end of next week.

**Comment by ejguan** [comment] 2023-01-25 22:03
If you use `DataLoader2`, this problem should have been fixed by https://github.com/pytorch/data/pull/950
```py
rs = PrototypeMultiprocessingReadingService(num_workers=NUM_WORKERS)
dl = DataLoader2(datapipe, reading_service=rs)
```

**Comment by ejguan** [comment] 2023-01-26 17:05
I am closing this issue as the patch has been landed. Please feel free to re-open it if the problem persists.

**Closed by ejguan** 2023-01-26 17:05 UTC
Labels: high priority
